#https://docs.spring.io/spring-boot/appendix/application-properties/index.html#appendix.application-properties.core

#spring.application.name=quickstart
#server.port=8181

server:
  port: 8282

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    

